/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientapp;

import DbConnection.ConnectionDB;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zoranhome
 */
public class addPatientDiagnosis extends javax.swing.JFrame {

    /**
     * Creates new form addPatientDiagnosis
     */
    private int flag = 0;

    public addPatientDiagnosis() {
        initComponents();
        setSize(985, 543);
        setLocation(280, 150);

        pogresanBrojLB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        IDbrojTF = new javax.swing.JTextField();
        pogresanBrojLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ljekoviTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        dijagnozaTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        napomenaTA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        simptomiTA = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        mainTableTBL = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        sacuvajBTN = new javax.swing.JButton();
        otkaziBTN = new javax.swing.JButton();
        traziBTN = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("ID BROJ");

        pogresanBrojLB.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        pogresanBrojLB.setForeground(new java.awt.Color(255, 51, 51));
        pogresanBrojLB.setText("Pogresan ID broj");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Simptomi");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Dijagnoza");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Ljekovi");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("Napomena");

        ljekoviTA.setColumns(20);
        ljekoviTA.setRows(5);
        jScrollPane1.setViewportView(ljekoviTA);

        dijagnozaTA.setColumns(20);
        dijagnozaTA.setRows(5);
        jScrollPane2.setViewportView(dijagnozaTA);

        napomenaTA.setColumns(20);
        napomenaTA.setRows(5);
        jScrollPane3.setViewportView(napomenaTA);

        simptomiTA.setColumns(20);
        simptomiTA.setRows(5);
        jScrollPane4.setViewportView(simptomiTA);

        mainTableTBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainTableTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nil", "nil", "nil", "nil"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "name", "age", "gender", "bloodGroup"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTableTBL.setColumnSelectionAllowed(true);
        mainTableTBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane6.setViewportView(mainTableTBL);
        mainTableTBL.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Korisnik");

        sacuvajBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sacuvajBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/save-icon--1.png"))); // NOI18N
        sacuvajBTN.setText("Sacuvaj");
        sacuvajBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajBTNActionPerformed(evt);
            }
        });

        otkaziBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        otkaziBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/Close.png"))); // NOI18N
        otkaziBTN.setText("Otkazi");
        otkaziBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otkaziBTNActionPerformed(evt);
            }
        });

        traziBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        traziBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/search.png"))); // NOI18N
        traziBTN.setText("Trazi");
        traziBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pogresanBrojLB)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IDbrojTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(traziBTN)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sacuvajBTN)
                                .addGap(196, 196, 196)
                                .addComponent(otkaziBTN)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane6))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pogresanBrojLB)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDbrojTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(traziBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel4)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel5)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sacuvajBTN)
                                    .addComponent(otkaziBTN))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otkaziBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otkaziBTNActionPerformed
        // Otkazi btn
        setVisible(false);
    }//GEN-LAST:event_otkaziBTNActionPerformed

    private void traziBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziBTNActionPerformed
//       Search for patient in db
        String patientId = IDbrojTF.getText();

        try (Connection dbConnection = ConnectionDB.getConn()) {

            Statement st = dbConnection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            String query = "SELECT name, age , gender, bloodGroup FROM dentaldb.pacijentbaza WHERE idpacijentbaza=" + patientId;

//            Get patient from db
            ResultSet rs = st.executeQuery(query);

//            add rs2xml.jar to populate table
            mainTableTBL.setModel(DbUtils.resultSetToTableModel(rs));

//               Check if patient returned
            if (!rs.first()) {
                pogresanBrojLB.setVisible(true);
                IDbrojTF.setText("");

            } else {
                pogresanBrojLB.setVisible(false);
                flag = 1;
            }

        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Problem: " + e.getLocalizedMessage());

        }
    }//GEN-LAST:event_traziBTNActionPerformed

    private void sacuvajBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajBTNActionPerformed
        // Add diagnosis
        if (flag == 1) {
//            Get user input data
            String patientId = IDbrojTF.getText();
            String symptoms = simptomiTA.getText();
            String diagnosis = dijagnozaTA.getText();
            String drugs = ljekoviTA.getText();
            String remarks = napomenaTA.getText();
            
            
            if(patientId.isEmpty() || symptoms.isEmpty() || diagnosis.isEmpty() || drugs.isEmpty() || remarks.isEmpty()){
                System.err.println("Input cannot be empty");
                JOptionPane.showMessageDialog(null, "Provjerite svoj unos. Polja ne mogu da budu prazna.","Select",JOptionPane.OK_OPTION);
            }else{
                
//            Establish db connection
            try (Connection dbConnection = ConnectionDB.getConn();) {

                Statement st = dbConnection.createStatement();

                st.executeUpdate("INSERT INTO `dentaldb`.`pacijentpregled` (`idpacijentpregled`, `symptoms`, `diagnosis`, `drugs`,`remarks`) VALUES ('" + patientId + "', '" + symptoms + "', '" + diagnosis + "', '" + drugs + "', '" + remarks + "');");

                JOptionPane.showMessageDialog(null, "Pregled sacuvan.", "Select", JOptionPane.YES_OPTION);
                        

                IDbrojTF.setText("");
                simptomiTA.setText("");
                dijagnozaTA.setText("");
                ljekoviTA.setText("");
                napomenaTA.setText("");
                flag = 0;

            } catch (Exception e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Provjerite svoj unos.","Select",JOptionPane.OK_OPTION);

            }
            }


        } else {
            JOptionPane.showMessageDialog(null, "Provjerite svoj unos.", "Select", JOptionPane.OK_OPTION);

        }
    }//GEN-LAST:event_sacuvajBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPatientDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPatientDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPatientDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPatientDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPatientDiagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDbrojTF;
    private javax.swing.JTextArea dijagnozaTA;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea ljekoviTA;
    private javax.swing.JTable mainTableTBL;
    private javax.swing.JTextArea napomenaTA;
    private javax.swing.JButton otkaziBTN;
    private javax.swing.JLabel pogresanBrojLB;
    private javax.swing.JButton sacuvajBTN;
    private javax.swing.JTextArea simptomiTA;
    private javax.swing.JButton traziBTN;
    // End of variables declaration//GEN-END:variables
}
