/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientapp;

import DbConnection.ConnectionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zoranhome
 */
public class patientHistory extends javax.swing.JFrame {

    /**
     * Creates new form patientHistory
     */
    public patientHistory() {
        initComponents();
        setSize(709, 498);
        setLocation(280, 150);
        pogresanIdBrojLBL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTBL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        idBrojTF = new javax.swing.JTextField();
        traziBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pogresanIdBrojLBL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTBL.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(153, 153, 153)));
        mainTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTBL.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(mainTBL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 6, 479, 490));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Istorija korisnika");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 203, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID Broj");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, 203, -1));
        getContentPane().add(idBrojTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 203, -1));

        traziBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        traziBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/search.png"))); // NOI18N
        traziBTN.setText("Trazi");
        traziBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziBTNActionPerformed(evt);
            }
        });
        getContentPane().add(traziBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 203, -1));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setText("Izlaz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 203, -1));

        pogresanIdBrojLBL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        pogresanIdBrojLBL.setForeground(new java.awt.Color(255, 51, 51));
        pogresanIdBrojLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pogresanIdBrojLBL.setText("Provjerite ID broj");
        pogresanIdBrojLBL.setToolTipText("Korisnik nije unesen u bazi");
        getContentPane().add(pogresanIdBrojLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 203, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/add new patient background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //exit frame
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void traziBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziBTNActionPerformed
        // Show patient history
        String idBroj = idBrojTF.getText();

        if (idBroj.isEmpty()) {

            System.err.println("Input cannot be empty");
            JOptionPane.showMessageDialog(null, "Provjerite svoj unos. Polja ne mogu da budu prazna.", "Select", JOptionPane.OK_OPTION);

        } else {

 //            Display data in table
            try (Connection dbConnection = ConnectionDB.getConn()) {

                Statement st = dbConnection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

                String query = "SELECT * FROM dentaldb.pacijentpregled WHERE idpacijentpregled=" + idBroj;

//                  Get patient from DB
                ResultSet rs = st.executeQuery(query);

//                add rs2xml.jar to populate table
                mainTBL.setModel(DbUtils.resultSetToTableModel(rs));

                if (!rs.first()) {
                    pogresanIdBrojLBL.setVisible(true);
                    idBrojTF.setText("");
                } else {
                    pogresanIdBrojLBL.setVisible(false);
                }
//             
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Connection error in: " + getClass());
            }
        }

    }//GEN-LAST:event_traziBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idBrojTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable mainTBL;
    private javax.swing.JLabel pogresanIdBrojLBL;
    private javax.swing.JButton traziBTN;
    // End of variables declaration//GEN-END:variables
}
