/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientapp;

import DbConnection.ConnectionDB;
import dentalswing.updatePatientRecord;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author zoranhome
 */
public class updateDelete extends javax.swing.JFrame {

    /**
     * Creates new form updateDelete
     */
    public updateDelete() {
        initComponents();
        setSize(454, 470);
        setLocation(280, 150);
        setResizable(false);
        noIdNumberLBL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idBrojTF = new javax.swing.JTextField();
        imeTF = new javax.swing.JTextField();
        brojTelefonaTF = new javax.swing.JTextField();
        polTF = new javax.swing.JTextField();
        adresaTF = new javax.swing.JTextField();
        sacuvatiBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        noIdNumberLBL = new javax.swing.JLabel();
        traziBTN = new javax.swing.JButton();
        krvnaGrupaTF = new javax.swing.JTextField();
        starostTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID Broj");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 39, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Krvna grupa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 265, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Starost");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 174, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ime");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 84, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Broj telefona");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 129, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pol");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Adresa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 309, -1, -1));
        getContentPane().add(idBrojTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 39, 124, -1));
        getContentPane().add(imeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 84, 124, -1));
        getContentPane().add(brojTelefonaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 129, 124, -1));
        getContentPane().add(polTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 124, -1));
        getContentPane().add(adresaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 309, 124, -1));

        sacuvatiBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sacuvatiBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/save-icon--1.png"))); // NOI18N
        sacuvatiBTN.setText("Sacuvati");
        sacuvatiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvatiBTNActionPerformed(evt);
            }
        });
        getContentPane().add(sacuvatiBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/Close.png"))); // NOI18N
        jButton2.setText("Obrisi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 111, -1));

        jButton3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton3.setText("Otkazi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 111, 32));

        noIdNumberLBL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        noIdNumberLBL.setForeground(new java.awt.Color(255, 51, 51));
        noIdNumberLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noIdNumberLBL.setText("Provjerite ID broj");
        noIdNumberLBL.setToolTipText("ID ne postoji u bazi korisnika");
        getContentPane().add(noIdNumberLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 16, -1, -1));

        traziBTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        traziBTN.setText("Trazi");
        traziBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziBTNActionPerformed(evt);
            }
        });
        getContentPane().add(traziBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 355, 112, -1));
        getContentPane().add(krvnaGrupaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 124, -1));
        getContentPane().add(starostTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 174, 123, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalswing/images/add new patient background.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sacuvatiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvatiBTNActionPerformed
        // Update user data

//        Get user input but no check included
        String idBroj = idBrojTF.getText();
        String ime = imeTF.getText();
        String brojTelefona = brojTelefonaTF.getText();
        String starost = starostTF.getText();
        String pol = polTF.getText();
        String krvnaGrupa = krvnaGrupaTF.getText();
        String adresa = adresaTF.getText();

//        connect and query db
        try (Connection dbConnection = ConnectionDB.getConn()) {
            // create statement
            Statement st = dbConnection.createStatement();
//            execute statement with query
            st.executeUpdate("UPDATE pacijentbaza SET name ='" + ime + "',contactNumber='" + brojTelefona + "',age='" + starost + "',gender='" + pol + "',bloodGroup='" + krvnaGrupa + "',address='" + adresa + "' WHERE idpacijentbaza='" + idBroj + "'");

            JOptionPane.showMessageDialog(null, "Successfully Updated");

            clearInput();

        } catch (Exception e) {
            System.err.println("Problem: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Check your input.");
        }

    }//GEN-LAST:event_sacuvatiBTNActionPerformed

    private void clearInput() {
        this.idBrojTF.setText("");
        this.imeTF.setText("");
        this.brojTelefonaTF.setText("");
        this.starostTF.setText("");
        this.polTF.setText("");
        this.krvnaGrupaTF.setText("");
        this.adresaTF.setText("");
    }
    


    private void traziBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziBTNActionPerformed
        // Get user id

//       Get patient id
        String patientId = idBrojTF.getText();

        try (Connection dbConnection = ConnectionDB.getConn()) {

            Statement st = dbConnection.createStatement();

            String query = "SELECT * FROM pacijentbaza WHERE idpacijentbaza = " + patientId;

//            Get patient from DB
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {

                imeTF.setText(rs.getString(2));
                brojTelefonaTF.setText(rs.getString(3));
                starostTF.setText(rs.getString(4));
                polTF.setText(rs.getString(5));
                krvnaGrupaTF.setText(rs.getString(6));
                adresaTF.setText(rs.getString(7));

                noIdNumberLBL.setVisible(false);

            } else {
                noIdNumberLBL.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection error in: " + getClass());
        }

    }//GEN-LAST:event_traziBTNActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Exit frame
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Delete user
        
        //       Get patient id
        String patientId = idBrojTF.getText();
        
         try (Connection dbConnection = ConnectionDB.getConn()) {

            Statement st = dbConnection.createStatement();
//            execute statement with query
            st.executeUpdate("DELETE FROM pacijentbaza WHERE idpacijentbaza='" + patientId + "'");

            JOptionPane.showMessageDialog(null, "Korisnik je ukolnjen iz baze");

            clearInput();

        } catch (Exception e) {
            System.err.println("Problem u brisanju korisnika iz baze" + e.getMessage());
            JOptionPane.showMessageDialog(null, "Provjerite ID broj.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresaTF;
    private javax.swing.JTextField brojTelefonaTF;
    private javax.swing.JTextField idBrojTF;
    private javax.swing.JTextField imeTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField krvnaGrupaTF;
    private javax.swing.JLabel noIdNumberLBL;
    private javax.swing.JTextField polTF;
    private javax.swing.JButton sacuvatiBTN;
    private javax.swing.JTextField starostTF;
    private javax.swing.JButton traziBTN;
    // End of variables declaration//GEN-END:variables
}
